with open('/mnt/workspace/.qwenpaw/workspaces/default/codex-termux/codex-termux-install.sh', 'r') as f:
    content = f.read()

old_section = """  # 主 config.toml — 只含 model_providers, 不含 profiles (v0.142.5+)
  {
    echo '# Auto-generated by codex-termux-install.sh'
    echo '# Do not edit manually — use switch-api commands'
    echo ''
    for i in \"${!keys[@]}\"; do
      printf '[model_providers.%s]\\n' \"${keys[$i]}\"
      printf 'name = \"%s\"\\n' \"${names[$i]}\"
      printf 'base_url = \"%s\"\\n' \"${urls[$i]}\"
      printf 'env_key = \"%s\"\\n' \"${envkeys[$i]}\"
      printf 'wire_api = \"responses\"\\n'
      printf 'requires_openai_auth = false\\n'
      echo ''
    done
  } > \"$CODEX_CONFIG_TOML\""""

new_section = """  # 主 config.toml — 含 profile = 行 (兼容 v0.141.x) + {profile}.config.toml (兼容 v0.142+)
  {
    echo '# Auto-generated by codex-termux-install.sh'
    echo '# Do not edit manually — use switch-api commands'
    echo ''
    printf 'profile = \"%s\"\\n' \"$active\"
    echo ''
    for i in \"${!keys[@]}\"; do
      printf '[model_providers.%s]\\n' \"${keys[$i]}\"
      printf 'name = \"%s\"\\n' \"${names[$i]}\"
      printf 'base_url = \"%s\"\\n' \"${urls[$i]}\"
      printf 'env_key = \"%s\"\\n' \"${envkeys[$i]}\"
      printf 'wire_api = \"responses\"\\n'
      printf 'requires_openai_auth = false\\n'
      echo ''
      printf '[profiles.%s]\\n' \"${keys[$i]}\"
      printf 'model = \"%s\"\\n' \"${models[$i]}\"
      printf 'model_provider = \"%s\"\\n' \"${keys[$i]}\"
      echo ''
    done
  } > \"$CODEX_CONFIG_TOML\""""

if old_section in content:
    content = content.replace(old_section, new_section, 1)
    with open('/mnt/workspace/.qwenpaw/workspaces/default/codex-termux/codex-termux-install.sh', 'w') as f:
        f.write(content)
    print("REPLACED OK")
else:
    print("NOT FOUND")
    idx = content.find('主 config.toml')
    print(content[idx:idx+400])
